#!/usr/bin/env -S make_rust_github_workflow --output_shell_completion wrap-command
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    # Group updates to reduce PR noise
    groups:
      cargo-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "rust"
